### ISSUE TITLE
Design and implement a notification message when a user creates an account

### ISSUE THREAD

**Issue by YaritzaGarcia** [uprm-inso-4101-2020-2021-S1/semester-project-team-tbd#31]
The purpose of this is that the user knows that he must confirm his email, through an email that will arrive, in order to use SyncLink.

Possible components: 
https://react-bootstrap.github.io/components/modal/
https://react-bootstrap.github.io/components/toasts/

![imagen](https://user-images.githubusercontent.com/39020809/95006760-a3d8cf00-05d5-11eb-9220-defe4dc1be2a.png)
![imagen](https://user-images.githubusercontent.com/39020809/95006777-dda9d580-05d5-11eb-9633-5d7434627b97.png)

**Comment by lukasslivko** [comment]
Do you just want to design a component that will be displayed after registration? You want both modal and toast
